# Generated by Django 2.0 on 2019-06-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=100)),
                ('pcost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pcolor', models.CharField(max_length=100)),
            ],
        ),
    ]
